### ISSUE TITLE
Criação do sistema de versão e branchs

### ISSUE THREAD

**Issue by igorgoncalves** [IgorGoncalves/nudesGo#2]

**Comment by MayaraMachado** [comment]
Projeto possui 2 branches constantes: Master e Develop. Geração dos branches Features e Hotfix ao decorrer do desenvolvimento.

**Comment by igorgoncalves** [comment]
@MayaraMachado  Quando você acha que é melhor fazer uma lançamento de versão? Semanal ?

**Comment by MayaraMachado** [comment]
@IgorGoncalves não sei se vai ficar um intervalo rápido para se ter versões rodando de forma estável,  mas acredito que dá pra lançar semanalmente
